### ISSUE TITLE
You can only test printable characters

### ISSUE THREAD

**Issue by PurpleBooth** [specdown/specdown#5]
There's a bunch of non-printable characters that's in stdout, and stderr

Colour codes, Bells, etc. Document how to use these, and add tests for them. I suspect some sort of escaping is needed?

**Comment by PurpleBooth** [comment]
Example #4

**Comment by tomphp** [comment]
https://github.com/specdown/specdown/commit/6000b44976c4e403daae8fcf2f96509591fe6391 strips all ANSI escape characters when doing the comparison. I feel this allows you to keep the docs looking tidy without adding weird escape chars. however, it doesn't let you test the colouring in the docs (maybe a future option can be added to make this possible).

Do you mind if I close this now?

**Comment by PurpleBooth** [comment]
Go for it, fixed!
